### ISSUE TITLE
Switch to React

### ISSUE THREAD

**Issue by nt1m** [nt1m/devtools-prototyper#36] opened 2015-07-25 19:29 UTC

**Comment by mdibaiee** [comment] 2015-07-26 01:42
React is awesome, and I think it can really help us organize the code, the only thing I'm a little worried about, which I think I shouldn't, is about integrating it with the rest of components (CodeMirror, etc).

I have a little experience using React, too, so I can help in case you decide to use React.

**Comment by nt1m** [comment] 2015-07-26 16:52
@mdibaiee This will surely clean the UI code. I've started a skeleton at [0] if you'd like to grab a look at it, the react stuff is in main.js, the old code is still there as a reference. I've added you as collaborator too so you have full access to this repo.

I have a few questions about using react though :
Should we separate the "backend" (non-UI) stuff from the UI code ? 
Is it a common practice to put each component into their own file ?

[0] : https://github.com/nt1m/devtools-prototyper/tree/react

**Comment by mdibaiee** [comment] 2015-07-26 19:29
@nt1m: I think it would help us maintain our code more easily by separating backend code from UI, we don't have to hunt down our functionality codes in our components, instead they have their own files, organized

Yes, I used React once in one of my projects and separating components was a good decision I took. Also I've seen others doing this, too, it's a good practice in my opinion. :+1:

I'll take a look tomorrow, and thanks for giving me permission

**Comment by mdibaiee** [comment] 2015-07-28 03:24
@nt1m: Hey, I like the new structure :+1:

A few ideas:

* I see you're creating class instances of Editor, Editors, SidebarButton, etc. in `app.js`, why not create a file for each and import the class from there, I know it make make for a lot of files, but the code looks more organized this way in my opinion.
* Do we need `Element` now that we have JSX?
* Would you agree on using the Developer Tools' `.eslintrc`?
* Also, we could unify the build system and use Grunt or Gulp to pre-compile our JSX templates, etc, and create the `.xpi` package, I think this is something we should do after refactoring.

I'll be waiting to hear your idea on the roadmap and follow it

**Comment by nt1m** [comment] 2015-07-28 23:27
<blockquote>
Hey, I like the new structure :+1:
</blockquote>
Thanks !

<blockquote>
I see you're creating class instances of Editor, Editors, SidebarButton, etc. in app.js, why not create a file for each and import the class from there, I know it make make for a lot of files, but the code looks more organized this way in my opinion.
</blockquote>
Yeah, we should do that. We can put the classes in components, and have a view.js file that controls those classes. 

<blockquote>
Do we need Element now that we have JSX?
</blockquote>
We don't, I just didn't remove the old files yet, since it's more convenient for copy-pasting. But Element is safe to remove.

<blockquote>
Would you agree on using the Developer Tools' .eslintrc?
</blockquote>
Sounds good, it'll also help us keep the code clean. This change should be on the main branch though.

<blockquote>
Also, we could unify the build system and use Grunt or Gulp to pre-compile our JSX templates, etc, and create the .xpi package, I think this is something we should do after refactoring.
</blockquote>
Yeah, let's use grunt for the build system, I've never used gulp before, but if there's a clear advantage over grunt, I'll be fine with it as well. In both cases, it will let us create more commands in the future too. 

<blockquote>
I'll be waiting to hear your idea on the roadmap and follow it
</blockquote>

About the roadmap, here's what I had in mind : 
- Create a JS file controlling all the react classes (the current main.js)
- Put the react classes in the components folder (I'm not too sure about the name though)
- Have another JS file with the logic in it (either panel.js, or a separate file, I'm not too sure what is the best solution)
- I also think it makes sense to move helpers.js to the top level chrome/ directory
What do you think ?


Thanks for helping with this btw !

**Comment by mdibaiee** [comment] 2015-07-29 08:12
Hey!

I pushed to my forked repository, as the commit is very big, I want you to review it, I'll list what's changed:

* Configured Grunt to:
  * Precompile JSX to JS
  * Run ESLint on JS and JSX files (+ eslint-plugin-react)
  * Create the XPI file
* Organized components into folders and modified some of the code:
  * React doesn't work with XML attributes, instead it uses the javascript properties, so attributes like
    `class` don't work, you have to use `className` instead
* Put the old codes into a folder called `old`
* Converted all tabs to spaces (eslint complains about tabs)

A few ideas:
* I see DevTools is using this kind of dropdown menus: 
<img width="328" alt="screen shot 1394-05-07 at 12 33 44" src="https://cloud.githubusercontent.com/assets/2807772/8952646/021d0864-35ee-11e5-9d33-973487bd6c97.png">

What do you think about using the same native thing instead of our dropdown?
* Organize backend code into separate files, just like components, in a folder like `logic`, `backend`, `services`, or something like that, we could even separate helpers, so no need to require the whole helpers file if we only need `Storage` for example.

Question:
I'm not very familiar with the way Firefox Add-ons work, trying to get the new code working, I encountered a problem with globals:

It seems using `require` doesn't inherit the global variables, I added `react.js` in an `<script>` tag, but `all.js` file complains about React being not defined (require(`all.js`)), I tried requiring React in the code, didn't work either, what's the solution?

Also, I see we have to use the prefix `chrome://devtools-prototyper/content` in order to require js files, is there any way to get relative requires working?

Thanks Tim! Sorry for the monster comment

**Comment by nt1m** [comment] 2015-07-29 14:50
<blockquote>
I pushed to my forked repository, as the commit is very big, I want you to review it, I'll list what's changed:

    Configured Grunt to:
        Precompile JSX to JS
        Run ESLint on JS and JSX files (+ eslint-plugin-react)
        Create the XPI file
    Organized components into folders and modified some of the code:
        React doesn't work with XML attributes, instead it uses the javascript properties, so attributes like class don't work, you have to use className instead
    Put the old codes into a folder called old
    Converted all tabs to spaces (eslint complains about tabs)
</blockquote>
The changes look good to me ! The original reason I've used tabs is because saves some file size (1 character instead of X spaces), it's also configurable to the user's preference. But most projects use 2 spaces anyway, so there's not much reason not to follow them.
About the JSX files, the JS is the compiled file, and the JSX is the source file right ? If so, is it a common practice to keep both ?

<blockquote>
What do you think about using the same native thing instead of our dropdown?
</blockquote>
As long as it doesn't involve using XUL, I'm fine with it. The addon used to emulate native menus, but with HTML I couldn't get a reliable copy, so I just used custom styled menus.

<blockquote>
Organize backend code into separate files, just like components, in a folder like logic, backend, services, or something like that, we could even separate helpers, so no need to require the whole helpers file if we only need Storage for example.
</blockquote>
I like that change ! I like backend as name.

<blockquote>
I'm not very familiar with the way Firefox Add-ons work, trying to get the new code working, I encountered a problem with globals:

It seems using require doesn't inherit the global variables, I added react.js in an `&lt;script>` tag, but all.js file complains about React being not defined (require(all.js)), I tried requiring React in the code, didn't work either, what's the solution?
</blockquote>
I'll try to ask on IRC later today. If you're requiring React, you should make sure exports.React is defined. Meanwhile, you can check Firefox Hello's code : https://dxr.mozilla.org/mozilla-central/search?q=require%28+path%3Abrowser%2Fcomponents%2Floop&case=false
It uses React as well, and may answer your questions.

<blockquote>
Also, I see we have to use the prefix chrome://devtools-prototyper/content in order to require js files, is there any way to get relative requires working?
</blockquote>
I don't know how to get relative requires working, I've tried require("foo") and require("../foo"), but they all add resource://gre/modules/ at the beginning of their path. I'll ask on IRC.

**Comment by mdibaiee** [comment] 2015-07-30 06:29
> About the JSX files, the JS is the compiled file, and the JSX is the source file right ? If so, is it a common practice to keep both ?
Yes, that makes future modifications easy, you just modify your JSX file and get a JS out, that's what Firefox Hello is doing, too.
> As long as it doesn't involve using XUL, I'm fine with it. The addon used to emulate native menus, but with HTML I couldn't get a reliable copy, so I just used custom styled menus.
I'll try to see if I can get it working with a `<select>` element.

----
It seems Firefox Hello is not using `require` at all, like they gave up on it. They are manually adding `<script>` tags for each file. My idea is to use an injector here, see [`grunt-asset-injector`](https://www.npmjs.com/package/grunt-asset-injector). It will automatically add an script tag for each file, and in order to sort and prioritze tags, we can use number prefixes, so `0-button.js` comes before `1-sidebar.js`. What do you think?

**Comment by nt1m** [comment] 2015-07-31 18:58
<blockquote>
I'll try to see if I can get it working with a <select> element.
</blockquote>
This isn't a good idea, I think we can just stick we the custom menu for now. The select element doesn't look like a menu on Windows anyway.

<blockquote>
It seems Firefox Hello is not using require at all, like they gave up on it. They are manually adding <script> tags for each file. My idea is to use an injector here, see grunt-asset-injector. It will automatically add an script tag for each file, and in order to sort and prioritze tags, we can use number prefixes, so 0-button.js comes before 1-sidebar.js. What do you think?
</blockquote>
I like the idea of using an injector, but I don't like having to name files like this. If we'd want to add a new file, we'd have to rename all the files, which is not really convenient. Also, it's pretty confusing for new people looking at our code.
Maybe an ordered array in the grunt file would be better ?

**Comment by nt1m** [comment] 2015-07-31 19:05
<blockquote>
Edit:
Okay, pushed to my fork, and got it actually working, it's rendering a sample text. I'll wait for your review to continue.
</blockquote>
The code looks good, but I'd like to get the file name issue addressed.

Also, regarding the folder organization, instead of putting the original source (`src` folder) and the compiled source (everything else) side by side. I think it's better to have one `src` directory with all the original source, and have another `dist` directory with all the compiled code in it. Having compiled JS and source JSX in the `src` directory is fine though.

**Comment by mdibaiee** [comment] 2015-08-01 01:56
> Also, regarding the folder organization, instead of putting the original source (src folder) and the compiled source (everything else) side by side. I think it's better to have one src directory with all the original source, and have another dist directory with all the compiled code in it. Having compiled JS and source JSX in the src directory is fine though.

Sorry but I'm not sure I understood you, can you give an example of the file structure you'd like to see?

> This isn't a good idea, I think we can just stick we the custom menu for now. The select element doesn't look like a menu on Windows anyway.

Yeah I gave up on it, nevermind.

**Comment by nt1m** [comment] 2015-08-01 03:18
"Sorry but I'm not sure I understood you, can you give an example of the file structure you'd like to see?"
Unless I'm mistaken, the source files live in `src`, but that's just for Javascript. It'd be less confusing to have *all* source files in src. And when running a grunt task, the grunt task would duplicate the src folder, rename it to dist, then manipulate things there. The separation between compiled and original files is more obvious that way. Right now, it takes some time to understand that the chrome folder has the compiled code. Also, in the future, the CSS can also be compiled without any confusion.

Here's the file structure : 
.eslintrc
.jshintrc
.gitignore
CHANGELOG.md
README.md
Gruntfile.js
package.json
src 
\_ chrome
\_ skin
\_ locale
\_ bootstrap.js
\_ chrome.manifest
\_ install.rdf
dist (this will be gitignored, and grunt will generate it)
\_ same stuff as src, but compiled

**Comment by mdibaiee** [comment] 2015-08-01 05:31
Hey, okay I got it, see my fork.

I got the Editors working and now you can run your code.

One thing: I modified the way code is ran, instead of using blobs, etc, I'm using the new `sdk/tabs` module to open a new tab and modify it, with a fake name of `chrome://devtools-prototyper/content/prototype.html`. It's easier and removes the need to get the `toolbox` instance, which was causing trouble with React (the code is run in another scope).

**Comment by mdibaiee** [comment] 2015-08-01 05:33
(:bulb:) Do you think there's any chance of getting this integrated into Firefox Developer Tools?

**Comment by nt1m** [comment] 2015-08-01 22:21
<blockquote>
Hey, okay I got it, see my fork.

I got the Editors working and now you can run your code.
</blockquote>
Nice ! Just tried it out, works nicely, the editors are missing syntax highlighting though, but I guess you know that.

<blockquote>
One thing: I modified the way code is ran, instead of using blobs, etc, I'm using the new sdk/tabs module to open a new tab and modify it, with a fake name of chrome://devtools-prototyper/content/prototype.html. It's easier and removes the need to get the toolbox instance, which was causing trouble with React (the code is run in another scope).
</blockquote>
I've just tried the workflow, and it's not very convenient having to switch tabs and close the previous one everytime you run/refresh the code. Also, we don't need prototype.html, I'm sure running it on top of about:blank should work.

<blockquote>
(:bulb:) Do you think there's any chance of getting this integrated into Firefox Developer Tools?
</blockquote>
This needs RDP (remote debugging protocol) integration before it can be shipped in the DevTools, so the tool works with Firefox OS or Chrome (via WebIDE).
I've met some people working on DevTools in Paris at the beginning of this month, and apparently they have plans to somewhat mix WebIDE with the toolbox. With file editing built in the toolbox, I doubt they'll integrate this addon, but there's still room for hope :)

**Comment by mdibaiee** [comment] 2015-08-02 15:43
https://github.com/mdibaiee/devtools-prototyper/commit/f6be2a7f738268a2b888805865fc07307587928a

**Comment by mdibaiee** [comment] 2015-08-03 11:09
https://github.com/babel/grunt-babel/issues/38

**Comment by mdibaiee** [comment] 2015-08-07 15:26
It's sad that our work is delayed because of this issue, I really tried to find a way to workaround these problems, no way.

Curious: Why doesn't Firefox support `<input>` inserted as innerHTML? Throws an error: "Mismatched tag, expected </input>", but it should support void elements. Is there a bug for that?

**Comment by nt1m** [comment] 2015-08-07 19:20
@mdibaiee Not sure what you're trying, but these snippets work for me : `document.body.innerHTML="<div><input type='text' /><span></span></div>"` or `document.body.innerHTML="<div><input type='text' /></div>"` or even `document.body.innerHTML="<input type='text' />"`

**Comment by nt1m** [comment] 2015-08-07 19:21
It works when I paste them in the console at least

**Comment by mdibaiee** [comment] 2015-08-08 11:48
I mean without an enclosing slash, `<input type="text">`. <- this is the new standard, but doesn't work on Firefox.

**Comment by nt1m** [comment] 2015-08-08 12:41
@mdibaiee Filed : https://bugzilla.mozilla.org/show_bug.cgi?id=1192521 . Firefox was built way before HTML 5 was born, so there may be some remains of the old syntax.

<blockquote>
Edit: Pushed some changes to Libraries and applied your comments, still WIP, will inform you when they're ready.
</blockquote>
https://github.com/mdibaiee/devtools-prototyper/commit/f6be2a7f738268a2b888805865fc07307587928a is still the latest commit.

<blockquote>
( :bulb: ) I'd say let's unify the menus, so use the same style of menu for export / save instead of a dropdown, what do you say?
</blockquote>
The library menu uses the full height, while the export menu doesn't. Which is why I think it makes sense to keep the export menu a floating menu. But I can easily be convinced if you can put up a concept that looks good.

**Comment by nt1m** [comment] 2015-08-08 12:42
Btw, I don't understand why we can't use the enclosing slash version for now, does that break ?

**Comment by mdibaiee** [comment] 2015-08-08 21:14
It was the cause of React breaking, React was rendering input element without an enclosing slash, but they went back to using enclosing slashes.

seems I had forgot to push, pushed https://github.com/mdibaiee/devtools-prototyper/commit/6fdd66085c57d5f5c0d6e9d3286c0472eaac70ad

**Comment by nt1m** [comment] 2015-08-08 21:45
@mdibaiee Can you try changing panel.xhtml to an actual HTML file ? 
Here are the changes you need to make : 
- Rename panel.xhtml to panel.html (and change the references too)
- Remove xmlns="http://www.w3.org/1999/xhtml"
- Remove the string stuff in the HTML doctype
- Remove <?xml version="1.0" encoding="UTF-8"?>

**Comment by nt1m** [comment] 2015-08-08 22:19
Btw, can you .gitignore the `dist` directory ? Having it in the repo makes reviewing difficult, since it makes the file changes show twice in commits. Also, new contributors may update the `dist` directory instead of the `src` directory by mistake.

**Comment by nt1m** [comment] 2015-08-09 11:31
I'm going to test it in a few hours. The first thing I've noticed is that panel.html seems to be missing from the dist.

**Comment by mdibaiee** [comment] 2015-08-09 11:41
just rebuild, that's because of .gitignore

also, I made a task `grunt install` which sends the `.xpi` to Extension Auto Installer localhost:8888

**Comment by nt1m** [comment] 2015-08-09 16:21
@mdibaiee Nice !
Here are a couple of issues I've found : 
- Running code doesn't seem to work, just redirects me to `about:blank`, the issue started appearing when we started using `about:blank`, injecting the worker causes `window is null` from the add-on SDK as I mentioned before. My guess is that we are injecting things too early.
- Opening the settings doesn't close the libraries menu

Regarding the interface of the libraries menu : 
- We should remove "https://cdnjs.cloudflare.com/ajax/libs/" from the URL display, since it's pretty much being repeated for each result.
- The search results should be sorted backwards, we want to sort by popularity, but the API sorts by newest library, so the oldest ones are the most popular (See https://github.com/cdnjs/cdnjs/issues/5107 )
- Instead of keeping the `checked` indicator, I think it would be more useful to change it into a `remove` button. It should be much easier to do this now that we have the React state stuff.
- The injected items' text isn't cropped properly, which makes the remove icon invisible
- The search input should take all the toolbar width
- The results take bit too much space in my opinion (I would allocate 50% of the height)
- The badge should show on top of the icon, not under it

**Comment by mdibaiee** [comment] 2015-08-09 18:58
@nt1m 

* Weird, it's working for me, I'm listening on `ready` event to attach, see https://github.com/mdibaiee/devtools-prototyper/blob/react/src/chrome/backend/code.js#L27-L38
I'll try to make it work somehow
* Why should it?

---

* I wanted to say the same thing about `checked`.
* The results are currently taking `45%` height

About other thing, I will work on 'em. Thanks for your review.

**Comment by nt1m** [comment] 2015-08-09 19:13
@mdibaiee 
- I'm using nightly, so it may be specific to that channel
- That's the way it worked before. And it also makes sense to me to keep only one item checked.
- Yep, but it seems like it takes more than 50% height on your branch, I would stay to 45%.

**Comment by mdibaiee** [comment] 2015-08-09 19:15
@nt1m 

* I'm on Nightly, too. 42.0a1 (2015-08-03)
* Alright
* Um, so keep it untouched or reduce it?

**Comment by nt1m** [comment] 2015-08-09 19:20
@mdibaiee 
- I'll investigate a bit more
- Hmm, it seems like a layout problem rather than a height change, seems that it is currently taking 45% of the wrong height. Can you try adding `overflow-y: auto` to `.menu` ?

**Comment by mdibaiee** [comment] 2015-08-09 19:21
@nt1m I'll take a look tomorrow, going to sleep right now, good night :crescent_moon:

**Comment by nt1m** [comment] 2015-08-09 19:24
@mdibaiee Good night ! (I'm in GMT+1, so I've gonna sleep too)

**Comment by nt1m** [comment] 2015-08-10 16:53
mdibaiee : Nice progress on the last commit ! Didn't know about React mixins too.
Anyway, about the prototype not running, I found out what the problem is : both about:newtab and the add-on sdk run in the parent process, while the add-on sdk expects the content to be in the child process. But this works fine in non-e10s. A possible solution (although I haven't tried it), is to navigate to a data URI : `data:text/html, <html></html>`. We can then restore `prototype.html` if the latter doesn't work.
Regarding the UI, it generally looks good now, but I'll likely make some tweaks after the refactoring is done.

**Comment by mdibaiee** [comment] 2015-08-11 11:53
Tested `data:text/html, <html></html>` blob URL but it doesn't work on e10s, instead `prototype.html` works.

But I couldn't get `console` to work on the webpage console, it only logs to Browser Console. I tried `text/javascript` and `application/javascript`. Any ideas on this?

https://github.com/mdibaiee/devtools-prototyper/commit/454850ef1b4ece76a70af00927af9da656b335f5
https://github.com/mdibaiee/devtools-prototyper/commit/fe6072f25f50ea80862d532dc1b9ed7d1f219191

Also, it seems there was a problem with `.gitignore` not actually ignoring `dist` subfolders, fixed that in another commit. https://github.com/mdibaiee/devtools-prototyper/commit/3bc7008c360830318f01549bc5cd525c4cb925ee

**Comment by mdibaiee** [comment] 2015-08-11 17:00
Is our add-on signed? https://news.ycombinator.com/item?id=10038999

**Comment by nt1m** [comment] 2015-08-11 20:30
@mdibaiee Only the AMO version is signed, but for development purposes, you can set `xpinstall.signatures.required` to false.

**Comment by mdibaiee** [comment] 2015-08-14 12:45
https://github.com/mdibaiee/devtools-prototyper/commit/9a087151179c84e26f1de30b633f3232fd3cd31f

I'm not sure about our `Save locally` option, it seems pointless, maybe we should implement #15 instead.

Other than that, what's left?

**Comment by nt1m** [comment] 2015-08-14 16:48
@mdibaiee 
<blockquote>
mdibaiee@9a08715
mdibaiee@2975aa9
</blockquote>
r+ with nits fixed.

<blockquote>
I'm not sure about our Save locally option, it seems pointless, maybe we should implement #15 instead.
</blockquote>
It's useful when you want to turn your prototype into a full project. But yeah, #15 covers that use case better.
<blockquote>
Other than that, what's left?
</blockquote>
The only thing I have in mind is saving injected libs into Storage. Since libs are an essential part of the prototype, the dev may be surprised to see it's prototype no longer working after reopening Prototyper.

**Comment by mdibaiee** [comment] 2015-08-14 19:51
You're right about export UI.

Another idea hit me about the export menu:

Diving the Gist button into two, Public Gist and Private Gist, having a setting for that doesn't seem right, having to switch a setting only for that.

---

Oh, I have not got the injected libraries actually working, going to work on that asap.

**Comment by nt1m** [comment] 2015-08-14 20:00
@mdibaiee I like the Gist idea :+1: 
Something like this would be nice : 
Gist :    |  Public  |  Private
We can even have 2 separate items.

**Comment by nt1m** [comment] 2015-08-14 20:02
Maybe the title and description stuff could go in there.

**Comment by mdibaiee** [comment] 2015-08-15 15:01
https://github.com/mdibaiee/devtools-prototyper/commit/af79f35f304a258b77d2a280a5d2445272432eb3

**Comment by nt1m** [comment] 2015-08-15 18:20
@mdibaiee : Nice ! Just tried it out, works quite well.
Here are a few bugs I've encountered though : 
- "initialized" storage entry gets synced
- The default value of injected-libraries breaks the add-on. The default value should be an array, other wise the add-on will throw (this.state.libraries.map is undefined)
- Secret gists get submitted under the "anonymous" account even when logged in
- Exporting to JSFiddle or Codepen doesn't seem to work with e10s enabled (although this is not a regression).

**Comment by mdibaiee** [comment] 2015-08-15 18:53
Actually even public gists will be submitted as guest, we must authorize our app with GitHub in order for that to work (also the user should accept the permissions), going to work on that tomorrow.

**Comment by mdibaiee** [comment] 2015-08-16 09:57
About e10s bug, It seems to be a problem with target=_blank on form, removing that works well (but you know it opens in the iframe itself).

I asked on IRC, didn't get a good answer, also couldn't find a [related] bug, can you please ask someone who might know about this? If it's not a known problem I can fill a bug

**Comment by nt1m** [comment] 2015-08-16 12:37
@mdibaiee One possibility to fix this is to run the form stuff as a content script in a new tab.

**Comment by mdibaiee** [comment] 2015-08-16 12:38
@nt1m: Good idea, will take a look at night, gotta go now.

**Comment by mdibaiee** [comment] 2015-08-16 20:12
@nt1m: It doesn't seem to work, I think I found the actual problem, the problem is `POST` requests don't work properly under e10s, I tried your idea, but it seems my requests just get sent as `GET` afterall, even though I set `method = "POST"`.

Searching for related bugs I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=1060367

**Comment by nt1m** [comment] 2015-08-16 20:25
@mdibaiee Weird, POST requests seem to work fine when exclusively done in the child process (testcase : https://startpage.com/eng/?&hmb=1). e10s issues are usually due to breakage with communication between parent/child process, I'm quite surprised that didn't work. Maybe content scripts run in the parent process ?

**Comment by mdibaiee** [comment] 2015-08-17 10:55
I don't have a good understanding of this concept, do you have any reference link so I can read more about how these processes communicate?

---

What's the idea now?

**Comment by nt1m** [comment] 2015-08-17 11:45
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by mdibaiee** [comment] 2015-08-18 19:45
This is really weird, I tried appending form to parent XULWindow, didn't work either. Do you think we should fill a bug in Firefox? and probably ignore this for now?

---

Anything else left so I can finish those first?

**Comment by nt1m** [comment] 2015-08-19 11:36
@mdibaiee Yeah, we should probably ignore this for now. Also, appending the form to the parent XUL Window, will likely cause the location to change on the parent window as well. 

There's still these to handle : 
- "initialized" storage entry gets synced
- The default value of injected-libraries breaks the add-on. The default value should be an array, other wise the add-on will throw (this.state.libraries.map is undefined)
- we should keep the html/css/js old pref names (or migrate them), since devs will lose their current prototypes upon upgrading. For injected-libs and settings, I'm fine with starting over so things are cleaner, especially since libs have a new data structure now (we used to only store the urls, now we're storing the names as well).

**Comment by mdibaiee** [comment] 2015-08-19 15:30
What were the old pref names? We're currently using `extensions.devtools-prototyper.editor-html`, isn't that the same as old ones?

_Man, what's wrong with .gitignore_

**Comment by nt1m** [comment] 2015-08-19 16:53
@mdibaiee We used `extensions.devtools-prototyper.html`, `extensions.devtools-prototyper.css` and `extensions.devtools-prototyper.js`. The pref names didn't include "editor-" in them.

About, .gitignore, you need to write `dist/` in .gitignore, and delete all the dist files, then create a commit just for that.

**Comment by nt1m** [comment] 2015-08-19 16:54
There may be a command to fix the `.gitignore` without deleting the files manually, but I know that the manual method works.

**Comment by nt1m** [comment] 2015-08-22 12:56
r+ with this issue fixed : 
`TypeError: this.state.injected.map is not a function`
This is because the default value of injected-libraries isn't an array.

**Comment by nt1m** [comment] 2015-08-22 12:58
To reproduce it, you'll need to reset `extensions.devtools-prototyper.injected-libraries` in about:config, or simply install the add-on on a blank profile.

**Comment by mdibaiee** [comment] 2015-08-22 15:03
pushed to my fork.

There is an issue with JSFiddle, exporting to JSFiddle doesn't render line-breaks, it seems linebreaks are not sent over the actual POST request, why is that? I couldn't find anything by searching.

Another thing is, can you work on #15 ? I'm getting more and more busy these days, I doubt I'll find time to work on that one, else we'll just go with downloading the HTML.

**Comment by nt1m** [comment] 2015-08-22 17:56
<blockquote>
pushed to my fork.
</blockquote>
Thanks for your awesome work ! Feel free to merge with this master branch :)

<blockquote>
There is an issue with JSFiddle, exporting to JSFiddle doesn't render line-breaks, it seems linebreaks are not sent over the actual POST request, why is that? I couldn't find anything by searching.
</blockquote>
I'm not sure, I'll investigate.

<blockquote>
Another thing is, can you work on #15 ? I'm getting more and more busy these days, I doubt I'll find time to work on that one, else we'll just go with downloading the HTML.
</blockquote>
Sure. Will work on it.

**Comment by mdibaiee** [comment] 2015-08-22 20:22
Merged with master! :fireworks: :sparkles: :star2:

Going to close this, such a monster issue. This is the 64th comment. Wow.

**Closed by mdibaiee** 2015-08-22 20:22 UTC
Labels: cleanup

**Comment by nt1m** [comment] 2015-08-22 22:17
Awesome ! \o/ Nice work :)

My preferred way of contacting is email (ntim.bugs@gmail.com). Feel free to email me :)
